package com.coins.tradecoin.entity;

import java.math.BigDecimal;
import java.util.Date;

public class OrderPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.type
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_price
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal orderPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_amount
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.processed_amount
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal processedAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.vot
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal vot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.fee
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.huobi_order_id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private Long huobiOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.platform_order_id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private Long platformOrderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.type
     *
     * @return the value of order.type
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.type
     *
     * @param type the value for order.type
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_price
     *
     * @return the value of order.order_price
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_price
     *
     * @param orderPrice the value for order.order_price
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_amount
     *
     * @return the value of order.order_amount
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_amount
     *
     * @param orderAmount the value for order.order_amount
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.processed_amount
     *
     * @return the value of order.processed_amount
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getProcessedAmount() {
        return processedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.processed_amount
     *
     * @param processedAmount the value for order.processed_amount
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setProcessedAmount(BigDecimal processedAmount) {
        this.processedAmount = processedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.vot
     *
     * @return the value of order.vot
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getVot() {
        return vot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.vot
     *
     * @param vot the value for order.vot
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setVot(BigDecimal vot) {
        this.vot = vot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.fee
     *
     * @return the value of order.fee
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.fee
     *
     * @param fee the value for order.fee
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total
     *
     * @return the value of order.total
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total
     *
     * @param total the value for order.total
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.huobi_order_id
     *
     * @return the value of order.huobi_order_id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public Long getHuobiOrderId() {
        return huobiOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.huobi_order_id
     *
     * @param huobiOrderId the value for order.huobi_order_id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setHuobiOrderId(Long huobiOrderId) {
        this.huobiOrderId = huobiOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.platform_order_id
     *
     * @return the value of order.platform_order_id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public Long getPlatformOrderId() {
        return platformOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.platform_order_id
     *
     * @param platformOrderId the value for order.platform_order_id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setPlatformOrderId(Long platformOrderId) {
        this.platformOrderId = platformOrderId;
    }
}