package com.leichuang.tradecoin.entity;

public class SettingPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setting.id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setting.type
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setting.attr_name
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private String attrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setting.attr_value
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private String attrValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setting.id
     *
     * @return the value of setting.id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setting.id
     *
     * @param id the value for setting.id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setting.type
     *
     * @return the value of setting.type
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setting.type
     *
     * @param type the value for setting.type
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setting.attr_name
     *
     * @return the value of setting.attr_name
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setting.attr_name
     *
     * @param attrName the value for setting.attr_name
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setting.attr_value
     *
     * @return the value of setting.attr_value
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setting.attr_value
     *
     * @param attrValue the value for setting.attr_value
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue;
    }
}