package com.leichuang.tradecoin.entity;

import java.math.BigDecimal;

public class UserPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account_id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_pwd
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private String loginPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.total
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.net_asset
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal netAsset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.available_cny_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal availableCnyDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.available_btc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal availableBtcDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.available_ltc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal availableLtcDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.frozen_cny_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal frozenCnyDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.frozen_btc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal frozenBtcDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.frozen_ltc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal frozenLtcDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.loan_cny_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal loanCnyDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.loan_btc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal loanBtcDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.loan_ltc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private BigDecimal loanLtcDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.huobi_access_key
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private String huobiAccessKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.huobi_secret_key
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    private String huobiSecretKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account
     *
     * @return the value of user.account
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account
     *
     * @param account the value for user.account
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account_id
     *
     * @return the value of user.account_id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account_id
     *
     * @param accountId the value for user.account_id
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_pwd
     *
     * @return the value of user.login_pwd
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_pwd
     *
     * @param loginPwd the value for user.login_pwd
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.total
     *
     * @return the value of user.total
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.total
     *
     * @param total the value for user.total
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.net_asset
     *
     * @return the value of user.net_asset
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getNetAsset() {
        return netAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.net_asset
     *
     * @param netAsset the value for user.net_asset
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setNetAsset(BigDecimal netAsset) {
        this.netAsset = netAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.available_cny_display
     *
     * @return the value of user.available_cny_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getAvailableCnyDisplay() {
        return availableCnyDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.available_cny_display
     *
     * @param availableCnyDisplay the value for user.available_cny_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setAvailableCnyDisplay(BigDecimal availableCnyDisplay) {
        this.availableCnyDisplay = availableCnyDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.available_btc_display
     *
     * @return the value of user.available_btc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getAvailableBtcDisplay() {
        return availableBtcDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.available_btc_display
     *
     * @param availableBtcDisplay the value for user.available_btc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setAvailableBtcDisplay(BigDecimal availableBtcDisplay) {
        this.availableBtcDisplay = availableBtcDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.available_ltc_display
     *
     * @return the value of user.available_ltc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getAvailableLtcDisplay() {
        return availableLtcDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.available_ltc_display
     *
     * @param availableLtcDisplay the value for user.available_ltc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setAvailableLtcDisplay(BigDecimal availableLtcDisplay) {
        this.availableLtcDisplay = availableLtcDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.frozen_cny_display
     *
     * @return the value of user.frozen_cny_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getFrozenCnyDisplay() {
        return frozenCnyDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.frozen_cny_display
     *
     * @param frozenCnyDisplay the value for user.frozen_cny_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setFrozenCnyDisplay(BigDecimal frozenCnyDisplay) {
        this.frozenCnyDisplay = frozenCnyDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.frozen_btc_display
     *
     * @return the value of user.frozen_btc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getFrozenBtcDisplay() {
        return frozenBtcDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.frozen_btc_display
     *
     * @param frozenBtcDisplay the value for user.frozen_btc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setFrozenBtcDisplay(BigDecimal frozenBtcDisplay) {
        this.frozenBtcDisplay = frozenBtcDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.frozen_ltc_display
     *
     * @return the value of user.frozen_ltc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getFrozenLtcDisplay() {
        return frozenLtcDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.frozen_ltc_display
     *
     * @param frozenLtcDisplay the value for user.frozen_ltc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setFrozenLtcDisplay(BigDecimal frozenLtcDisplay) {
        this.frozenLtcDisplay = frozenLtcDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.loan_cny_display
     *
     * @return the value of user.loan_cny_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getLoanCnyDisplay() {
        return loanCnyDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.loan_cny_display
     *
     * @param loanCnyDisplay the value for user.loan_cny_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setLoanCnyDisplay(BigDecimal loanCnyDisplay) {
        this.loanCnyDisplay = loanCnyDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.loan_btc_display
     *
     * @return the value of user.loan_btc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getLoanBtcDisplay() {
        return loanBtcDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.loan_btc_display
     *
     * @param loanBtcDisplay the value for user.loan_btc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setLoanBtcDisplay(BigDecimal loanBtcDisplay) {
        this.loanBtcDisplay = loanBtcDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.loan_ltc_display
     *
     * @return the value of user.loan_ltc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public BigDecimal getLoanLtcDisplay() {
        return loanLtcDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.loan_ltc_display
     *
     * @param loanLtcDisplay the value for user.loan_ltc_display
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setLoanLtcDisplay(BigDecimal loanLtcDisplay) {
        this.loanLtcDisplay = loanLtcDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.huobi_access_key
     *
     * @return the value of user.huobi_access_key
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public String getHuobiAccessKey() {
        return huobiAccessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.huobi_access_key
     *
     * @param huobiAccessKey the value for user.huobi_access_key
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setHuobiAccessKey(String huobiAccessKey) {
        this.huobiAccessKey = huobiAccessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.huobi_secret_key
     *
     * @return the value of user.huobi_secret_key
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public String getHuobiSecretKey() {
        return huobiSecretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.huobi_secret_key
     *
     * @param huobiSecretKey the value for user.huobi_secret_key
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setHuobiSecretKey(String huobiSecretKey) {
        this.huobiSecretKey = huobiSecretKey;
    }
}