package com.leichuang.tradecoin.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class UserPOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public UserPOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public UserPOExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public UserPOExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Criteria newAndCreateCriteria() {
        UserPOExample example = new UserPOExample();
        return example.createCriteria();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAccountIsNull() {
            addCriterion("account is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("account is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(String value) {
            addCriterion("account =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(String value) {
            addCriterion("account <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(String value) {
            addCriterion("account >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(String value) {
            addCriterion("account >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(String value) {
            addCriterion("account <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(String value) {
            addCriterion("account <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLike(String value) {
            addCriterion("account like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotLike(String value) {
            addCriterion("account not like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<String> values) {
            addCriterion("account in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<String> values) {
            addCriterion("account not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(String value1, String value2) {
            addCriterion("account between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(String value1, String value2) {
            addCriterion("account not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("account_id is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("account_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(String value) {
            addCriterion("account_id =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(String value) {
            addCriterion("account_id <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(String value) {
            addCriterion("account_id >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(String value) {
            addCriterion("account_id >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(String value) {
            addCriterion("account_id <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(String value) {
            addCriterion("account_id <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLike(String value) {
            addCriterion("account_id like", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotLike(String value) {
            addCriterion("account_id not like", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<String> values) {
            addCriterion("account_id in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<String> values) {
            addCriterion("account_id not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(String value1, String value2) {
            addCriterion("account_id between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(String value1, String value2) {
            addCriterion("account_id not between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIsNull() {
            addCriterion("login_pwd is null");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIsNotNull() {
            addCriterion("login_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andLoginPwdEqualTo(String value) {
            addCriterion("login_pwd =", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotEqualTo(String value) {
            addCriterion("login_pwd <>", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdGreaterThan(String value) {
            addCriterion("login_pwd >", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdGreaterThanOrEqualTo(String value) {
            addCriterion("login_pwd >=", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLessThan(String value) {
            addCriterion("login_pwd <", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLessThanOrEqualTo(String value) {
            addCriterion("login_pwd <=", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLike(String value) {
            addCriterion("login_pwd like", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotLike(String value) {
            addCriterion("login_pwd not like", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIn(List<String> values) {
            addCriterion("login_pwd in", values, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotIn(List<String> values) {
            addCriterion("login_pwd not in", values, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdBetween(String value1, String value2) {
            addCriterion("login_pwd between", value1, value2, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotBetween(String value1, String value2) {
            addCriterion("login_pwd not between", value1, value2, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andTotalIsNull() {
            addCriterion("total is null");
            return (Criteria) this;
        }

        public Criteria andTotalIsNotNull() {
            addCriterion("total is not null");
            return (Criteria) this;
        }

        public Criteria andTotalEqualTo(BigDecimal value) {
            addCriterion("total =", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotEqualTo(BigDecimal value) {
            addCriterion("total <>", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThan(BigDecimal value) {
            addCriterion("total >", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total >=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThan(BigDecimal value) {
            addCriterion("total <", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total <=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalIn(List<BigDecimal> values) {
            addCriterion("total in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotIn(List<BigDecimal> values) {
            addCriterion("total not in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total not between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andNetAssetIsNull() {
            addCriterion("net_asset is null");
            return (Criteria) this;
        }

        public Criteria andNetAssetIsNotNull() {
            addCriterion("net_asset is not null");
            return (Criteria) this;
        }

        public Criteria andNetAssetEqualTo(BigDecimal value) {
            addCriterion("net_asset =", value, "netAsset");
            return (Criteria) this;
        }

        public Criteria andNetAssetNotEqualTo(BigDecimal value) {
            addCriterion("net_asset <>", value, "netAsset");
            return (Criteria) this;
        }

        public Criteria andNetAssetGreaterThan(BigDecimal value) {
            addCriterion("net_asset >", value, "netAsset");
            return (Criteria) this;
        }

        public Criteria andNetAssetGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("net_asset >=", value, "netAsset");
            return (Criteria) this;
        }

        public Criteria andNetAssetLessThan(BigDecimal value) {
            addCriterion("net_asset <", value, "netAsset");
            return (Criteria) this;
        }

        public Criteria andNetAssetLessThanOrEqualTo(BigDecimal value) {
            addCriterion("net_asset <=", value, "netAsset");
            return (Criteria) this;
        }

        public Criteria andNetAssetIn(List<BigDecimal> values) {
            addCriterion("net_asset in", values, "netAsset");
            return (Criteria) this;
        }

        public Criteria andNetAssetNotIn(List<BigDecimal> values) {
            addCriterion("net_asset not in", values, "netAsset");
            return (Criteria) this;
        }

        public Criteria andNetAssetBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("net_asset between", value1, value2, "netAsset");
            return (Criteria) this;
        }

        public Criteria andNetAssetNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("net_asset not between", value1, value2, "netAsset");
            return (Criteria) this;
        }

        public Criteria andAvailableCnyDisplayIsNull() {
            addCriterion("available_cny_display is null");
            return (Criteria) this;
        }

        public Criteria andAvailableCnyDisplayIsNotNull() {
            addCriterion("available_cny_display is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableCnyDisplayEqualTo(BigDecimal value) {
            addCriterion("available_cny_display =", value, "availableCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableCnyDisplayNotEqualTo(BigDecimal value) {
            addCriterion("available_cny_display <>", value, "availableCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableCnyDisplayGreaterThan(BigDecimal value) {
            addCriterion("available_cny_display >", value, "availableCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableCnyDisplayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("available_cny_display >=", value, "availableCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableCnyDisplayLessThan(BigDecimal value) {
            addCriterion("available_cny_display <", value, "availableCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableCnyDisplayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("available_cny_display <=", value, "availableCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableCnyDisplayIn(List<BigDecimal> values) {
            addCriterion("available_cny_display in", values, "availableCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableCnyDisplayNotIn(List<BigDecimal> values) {
            addCriterion("available_cny_display not in", values, "availableCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableCnyDisplayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("available_cny_display between", value1, value2, "availableCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableCnyDisplayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("available_cny_display not between", value1, value2, "availableCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableBtcDisplayIsNull() {
            addCriterion("available_btc_display is null");
            return (Criteria) this;
        }

        public Criteria andAvailableBtcDisplayIsNotNull() {
            addCriterion("available_btc_display is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableBtcDisplayEqualTo(BigDecimal value) {
            addCriterion("available_btc_display =", value, "availableBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableBtcDisplayNotEqualTo(BigDecimal value) {
            addCriterion("available_btc_display <>", value, "availableBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableBtcDisplayGreaterThan(BigDecimal value) {
            addCriterion("available_btc_display >", value, "availableBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableBtcDisplayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("available_btc_display >=", value, "availableBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableBtcDisplayLessThan(BigDecimal value) {
            addCriterion("available_btc_display <", value, "availableBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableBtcDisplayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("available_btc_display <=", value, "availableBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableBtcDisplayIn(List<BigDecimal> values) {
            addCriterion("available_btc_display in", values, "availableBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableBtcDisplayNotIn(List<BigDecimal> values) {
            addCriterion("available_btc_display not in", values, "availableBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableBtcDisplayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("available_btc_display between", value1, value2, "availableBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableBtcDisplayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("available_btc_display not between", value1, value2, "availableBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableLtcDisplayIsNull() {
            addCriterion("available_ltc_display is null");
            return (Criteria) this;
        }

        public Criteria andAvailableLtcDisplayIsNotNull() {
            addCriterion("available_ltc_display is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableLtcDisplayEqualTo(BigDecimal value) {
            addCriterion("available_ltc_display =", value, "availableLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableLtcDisplayNotEqualTo(BigDecimal value) {
            addCriterion("available_ltc_display <>", value, "availableLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableLtcDisplayGreaterThan(BigDecimal value) {
            addCriterion("available_ltc_display >", value, "availableLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableLtcDisplayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("available_ltc_display >=", value, "availableLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableLtcDisplayLessThan(BigDecimal value) {
            addCriterion("available_ltc_display <", value, "availableLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableLtcDisplayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("available_ltc_display <=", value, "availableLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableLtcDisplayIn(List<BigDecimal> values) {
            addCriterion("available_ltc_display in", values, "availableLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableLtcDisplayNotIn(List<BigDecimal> values) {
            addCriterion("available_ltc_display not in", values, "availableLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableLtcDisplayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("available_ltc_display between", value1, value2, "availableLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andAvailableLtcDisplayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("available_ltc_display not between", value1, value2, "availableLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenCnyDisplayIsNull() {
            addCriterion("frozen_cny_display is null");
            return (Criteria) this;
        }

        public Criteria andFrozenCnyDisplayIsNotNull() {
            addCriterion("frozen_cny_display is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenCnyDisplayEqualTo(BigDecimal value) {
            addCriterion("frozen_cny_display =", value, "frozenCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenCnyDisplayNotEqualTo(BigDecimal value) {
            addCriterion("frozen_cny_display <>", value, "frozenCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenCnyDisplayGreaterThan(BigDecimal value) {
            addCriterion("frozen_cny_display >", value, "frozenCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenCnyDisplayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("frozen_cny_display >=", value, "frozenCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenCnyDisplayLessThan(BigDecimal value) {
            addCriterion("frozen_cny_display <", value, "frozenCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenCnyDisplayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("frozen_cny_display <=", value, "frozenCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenCnyDisplayIn(List<BigDecimal> values) {
            addCriterion("frozen_cny_display in", values, "frozenCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenCnyDisplayNotIn(List<BigDecimal> values) {
            addCriterion("frozen_cny_display not in", values, "frozenCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenCnyDisplayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("frozen_cny_display between", value1, value2, "frozenCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenCnyDisplayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("frozen_cny_display not between", value1, value2, "frozenCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenBtcDisplayIsNull() {
            addCriterion("frozen_btc_display is null");
            return (Criteria) this;
        }

        public Criteria andFrozenBtcDisplayIsNotNull() {
            addCriterion("frozen_btc_display is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenBtcDisplayEqualTo(BigDecimal value) {
            addCriterion("frozen_btc_display =", value, "frozenBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenBtcDisplayNotEqualTo(BigDecimal value) {
            addCriterion("frozen_btc_display <>", value, "frozenBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenBtcDisplayGreaterThan(BigDecimal value) {
            addCriterion("frozen_btc_display >", value, "frozenBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenBtcDisplayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("frozen_btc_display >=", value, "frozenBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenBtcDisplayLessThan(BigDecimal value) {
            addCriterion("frozen_btc_display <", value, "frozenBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenBtcDisplayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("frozen_btc_display <=", value, "frozenBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenBtcDisplayIn(List<BigDecimal> values) {
            addCriterion("frozen_btc_display in", values, "frozenBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenBtcDisplayNotIn(List<BigDecimal> values) {
            addCriterion("frozen_btc_display not in", values, "frozenBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenBtcDisplayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("frozen_btc_display between", value1, value2, "frozenBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenBtcDisplayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("frozen_btc_display not between", value1, value2, "frozenBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenLtcDisplayIsNull() {
            addCriterion("frozen_ltc_display is null");
            return (Criteria) this;
        }

        public Criteria andFrozenLtcDisplayIsNotNull() {
            addCriterion("frozen_ltc_display is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenLtcDisplayEqualTo(BigDecimal value) {
            addCriterion("frozen_ltc_display =", value, "frozenLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenLtcDisplayNotEqualTo(BigDecimal value) {
            addCriterion("frozen_ltc_display <>", value, "frozenLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenLtcDisplayGreaterThan(BigDecimal value) {
            addCriterion("frozen_ltc_display >", value, "frozenLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenLtcDisplayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("frozen_ltc_display >=", value, "frozenLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenLtcDisplayLessThan(BigDecimal value) {
            addCriterion("frozen_ltc_display <", value, "frozenLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenLtcDisplayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("frozen_ltc_display <=", value, "frozenLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenLtcDisplayIn(List<BigDecimal> values) {
            addCriterion("frozen_ltc_display in", values, "frozenLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenLtcDisplayNotIn(List<BigDecimal> values) {
            addCriterion("frozen_ltc_display not in", values, "frozenLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenLtcDisplayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("frozen_ltc_display between", value1, value2, "frozenLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andFrozenLtcDisplayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("frozen_ltc_display not between", value1, value2, "frozenLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanCnyDisplayIsNull() {
            addCriterion("loan_cny_display is null");
            return (Criteria) this;
        }

        public Criteria andLoanCnyDisplayIsNotNull() {
            addCriterion("loan_cny_display is not null");
            return (Criteria) this;
        }

        public Criteria andLoanCnyDisplayEqualTo(BigDecimal value) {
            addCriterion("loan_cny_display =", value, "loanCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanCnyDisplayNotEqualTo(BigDecimal value) {
            addCriterion("loan_cny_display <>", value, "loanCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanCnyDisplayGreaterThan(BigDecimal value) {
            addCriterion("loan_cny_display >", value, "loanCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanCnyDisplayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("loan_cny_display >=", value, "loanCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanCnyDisplayLessThan(BigDecimal value) {
            addCriterion("loan_cny_display <", value, "loanCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanCnyDisplayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("loan_cny_display <=", value, "loanCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanCnyDisplayIn(List<BigDecimal> values) {
            addCriterion("loan_cny_display in", values, "loanCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanCnyDisplayNotIn(List<BigDecimal> values) {
            addCriterion("loan_cny_display not in", values, "loanCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanCnyDisplayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("loan_cny_display between", value1, value2, "loanCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanCnyDisplayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("loan_cny_display not between", value1, value2, "loanCnyDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanBtcDisplayIsNull() {
            addCriterion("loan_btc_display is null");
            return (Criteria) this;
        }

        public Criteria andLoanBtcDisplayIsNotNull() {
            addCriterion("loan_btc_display is not null");
            return (Criteria) this;
        }

        public Criteria andLoanBtcDisplayEqualTo(BigDecimal value) {
            addCriterion("loan_btc_display =", value, "loanBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanBtcDisplayNotEqualTo(BigDecimal value) {
            addCriterion("loan_btc_display <>", value, "loanBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanBtcDisplayGreaterThan(BigDecimal value) {
            addCriterion("loan_btc_display >", value, "loanBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanBtcDisplayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("loan_btc_display >=", value, "loanBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanBtcDisplayLessThan(BigDecimal value) {
            addCriterion("loan_btc_display <", value, "loanBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanBtcDisplayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("loan_btc_display <=", value, "loanBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanBtcDisplayIn(List<BigDecimal> values) {
            addCriterion("loan_btc_display in", values, "loanBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanBtcDisplayNotIn(List<BigDecimal> values) {
            addCriterion("loan_btc_display not in", values, "loanBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanBtcDisplayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("loan_btc_display between", value1, value2, "loanBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanBtcDisplayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("loan_btc_display not between", value1, value2, "loanBtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanLtcDisplayIsNull() {
            addCriterion("loan_ltc_display is null");
            return (Criteria) this;
        }

        public Criteria andLoanLtcDisplayIsNotNull() {
            addCriterion("loan_ltc_display is not null");
            return (Criteria) this;
        }

        public Criteria andLoanLtcDisplayEqualTo(BigDecimal value) {
            addCriterion("loan_ltc_display =", value, "loanLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanLtcDisplayNotEqualTo(BigDecimal value) {
            addCriterion("loan_ltc_display <>", value, "loanLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanLtcDisplayGreaterThan(BigDecimal value) {
            addCriterion("loan_ltc_display >", value, "loanLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanLtcDisplayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("loan_ltc_display >=", value, "loanLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanLtcDisplayLessThan(BigDecimal value) {
            addCriterion("loan_ltc_display <", value, "loanLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanLtcDisplayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("loan_ltc_display <=", value, "loanLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanLtcDisplayIn(List<BigDecimal> values) {
            addCriterion("loan_ltc_display in", values, "loanLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanLtcDisplayNotIn(List<BigDecimal> values) {
            addCriterion("loan_ltc_display not in", values, "loanLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanLtcDisplayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("loan_ltc_display between", value1, value2, "loanLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andLoanLtcDisplayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("loan_ltc_display not between", value1, value2, "loanLtcDisplay");
            return (Criteria) this;
        }

        public Criteria andHuobiAccessKeyIsNull() {
            addCriterion("huobi_access_key is null");
            return (Criteria) this;
        }

        public Criteria andHuobiAccessKeyIsNotNull() {
            addCriterion("huobi_access_key is not null");
            return (Criteria) this;
        }

        public Criteria andHuobiAccessKeyEqualTo(String value) {
            addCriterion("huobi_access_key =", value, "huobiAccessKey");
            return (Criteria) this;
        }

        public Criteria andHuobiAccessKeyNotEqualTo(String value) {
            addCriterion("huobi_access_key <>", value, "huobiAccessKey");
            return (Criteria) this;
        }

        public Criteria andHuobiAccessKeyGreaterThan(String value) {
            addCriterion("huobi_access_key >", value, "huobiAccessKey");
            return (Criteria) this;
        }

        public Criteria andHuobiAccessKeyGreaterThanOrEqualTo(String value) {
            addCriterion("huobi_access_key >=", value, "huobiAccessKey");
            return (Criteria) this;
        }

        public Criteria andHuobiAccessKeyLessThan(String value) {
            addCriterion("huobi_access_key <", value, "huobiAccessKey");
            return (Criteria) this;
        }

        public Criteria andHuobiAccessKeyLessThanOrEqualTo(String value) {
            addCriterion("huobi_access_key <=", value, "huobiAccessKey");
            return (Criteria) this;
        }

        public Criteria andHuobiAccessKeyLike(String value) {
            addCriterion("huobi_access_key like", value, "huobiAccessKey");
            return (Criteria) this;
        }

        public Criteria andHuobiAccessKeyNotLike(String value) {
            addCriterion("huobi_access_key not like", value, "huobiAccessKey");
            return (Criteria) this;
        }

        public Criteria andHuobiAccessKeyIn(List<String> values) {
            addCriterion("huobi_access_key in", values, "huobiAccessKey");
            return (Criteria) this;
        }

        public Criteria andHuobiAccessKeyNotIn(List<String> values) {
            addCriterion("huobi_access_key not in", values, "huobiAccessKey");
            return (Criteria) this;
        }

        public Criteria andHuobiAccessKeyBetween(String value1, String value2) {
            addCriterion("huobi_access_key between", value1, value2, "huobiAccessKey");
            return (Criteria) this;
        }

        public Criteria andHuobiAccessKeyNotBetween(String value1, String value2) {
            addCriterion("huobi_access_key not between", value1, value2, "huobiAccessKey");
            return (Criteria) this;
        }

        public Criteria andHuobiSecretKeyIsNull() {
            addCriterion("huobi_secret_key is null");
            return (Criteria) this;
        }

        public Criteria andHuobiSecretKeyIsNotNull() {
            addCriterion("huobi_secret_key is not null");
            return (Criteria) this;
        }

        public Criteria andHuobiSecretKeyEqualTo(String value) {
            addCriterion("huobi_secret_key =", value, "huobiSecretKey");
            return (Criteria) this;
        }

        public Criteria andHuobiSecretKeyNotEqualTo(String value) {
            addCriterion("huobi_secret_key <>", value, "huobiSecretKey");
            return (Criteria) this;
        }

        public Criteria andHuobiSecretKeyGreaterThan(String value) {
            addCriterion("huobi_secret_key >", value, "huobiSecretKey");
            return (Criteria) this;
        }

        public Criteria andHuobiSecretKeyGreaterThanOrEqualTo(String value) {
            addCriterion("huobi_secret_key >=", value, "huobiSecretKey");
            return (Criteria) this;
        }

        public Criteria andHuobiSecretKeyLessThan(String value) {
            addCriterion("huobi_secret_key <", value, "huobiSecretKey");
            return (Criteria) this;
        }

        public Criteria andHuobiSecretKeyLessThanOrEqualTo(String value) {
            addCriterion("huobi_secret_key <=", value, "huobiSecretKey");
            return (Criteria) this;
        }

        public Criteria andHuobiSecretKeyLike(String value) {
            addCriterion("huobi_secret_key like", value, "huobiSecretKey");
            return (Criteria) this;
        }

        public Criteria andHuobiSecretKeyNotLike(String value) {
            addCriterion("huobi_secret_key not like", value, "huobiSecretKey");
            return (Criteria) this;
        }

        public Criteria andHuobiSecretKeyIn(List<String> values) {
            addCriterion("huobi_secret_key in", values, "huobiSecretKey");
            return (Criteria) this;
        }

        public Criteria andHuobiSecretKeyNotIn(List<String> values) {
            addCriterion("huobi_secret_key not in", values, "huobiSecretKey");
            return (Criteria) this;
        }

        public Criteria andHuobiSecretKeyBetween(String value1, String value2) {
            addCriterion("huobi_secret_key between", value1, value2, "huobiSecretKey");
            return (Criteria) this;
        }

        public Criteria andHuobiSecretKeyNotBetween(String value1, String value2) {
            addCriterion("huobi_secret_key not between", value1, value2, "huobiSecretKey");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 15 15:30:16 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private UserPOExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(UserPOExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public UserPOExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table user
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}