spring:
  application:
    name: tradecoin
  datasource:
    huobi:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      #    url: jdbc:mysql://localhost:3306/cf_act?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false
      #    username: root
      #    password: root
      url: jdbc:mysql://localhost:3306/huobi?useSSL=false
      username: root
      password: 12345678
      #-----------------------
      #下面为连接池补充设置
      initialSize: 5
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

huobi:
  api:
    access_key: sdfafda
    secret_key: sfasf
    url: sdfaf

trade:
  user:
    id: 1