package com.coins.tradecoin.dao;

import com.coins.tradecoin.entity.OrderPO;
import com.coins.tradecoin.entity.OrderPOExample;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    long countByExample(OrderPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    int insert(OrderPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    int insertSelective(OrderPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    List<OrderPO> selectByExample(OrderPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    OrderPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    int updateByPrimaryKeySelective(OrderPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    int updateByPrimaryKey(OrderPO record);
}