package com.leichuang.tradecoin.dao;

import com.leichuang.tradecoin.entity.SettingPO;
import com.leichuang.tradecoin.entity.SettingPOExample;
import java.util.List;

public interface SettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    long countByExample(SettingPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    int insert(SettingPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    int insertSelective(SettingPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    List<SettingPO> selectByExample(SettingPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    SettingPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    int updateByPrimaryKeySelective(SettingPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbg.generated Fri Mar 15 15:30:16 CST 2019
     */
    int updateByPrimaryKey(SettingPO record);
}